{% set name = "clikit" %}
{% set version = "0.3.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: 979a7442ca1be1eaa9fae3e0ab7d63828b85fd42ded2d6954340a8b926500b39

build:
  noarch: python
  number: 0
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - pip
    - python
    - poetry >=0.12
# clikit need poetry to build
# pip install clikit==0.3.0 --no-binary :all:

  run:
    - pastel >=0.1.0,<0.2.0
    - pylev >=1.3,<2.0
    - python

test:
  imports:
    - clikit

about:
  home: https://github.com/sdispater/clikit
  license: MIT
  license_family: MIT
  license_file: LICENSE 
  summary: "CliKit is a group of utilities to build beautiful and testable command line interfaces."

extra:
  recipe-maintainers:
    - roccqqck
    
