{% set version = "0.4.3" %}

package:
  name: clikit
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/c/clikit/clikit-{{ version }}.tar.gz
  sha256: 6e2d7e115e7c7b35bceb0209109935ab2f9ab50910e9ff2293f7fa0b7abf973e

build:
  number: 0
  # This needs selectors to build on py27 and py35
  # b/c conda-forge dropped py35 already and py27 reached EOL we'll make this noarch instead.
  noarch: python
  script:
    # clikit cannot depend on itself via poetry
    - rm -f pyproject.toml
    - {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python
    - pip
  run:
    - python
    - pastel >=0.2.0,<0.3.0
    - pylev >=1.3,<2.0

test:
  imports:
    - clikit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/sdispater/clikit
  license: MIT
  license_family: MIT
  license_file: LICENSE
  summary: CliKit is a group of utilities to build beautiful and testable command line interfaces.

extra:
  recipe-maintainers:
    - roccqqck
    - ocefpaf
